# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: eb46ca5744a727b3120945f23c802805f7399dbf4e52e68e7da15ef2c1d19c4e26a0123648ab9a76d4722c1e992901567481211bbf50dc9ac30bd25209399d57

test:
  secret_key_base: b8c86862bdcfd88e82cd31613a27a4672b7e6936c8cf963c4125f46f723a8330059d30b625a9c7cd572413a2c7edf4f9b271ea420d4720ff39c11ee0ef4b2905

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
